### ISSUE TITLE
Bindable options are not working

### ISSUE THREAD

**Issue by jeffgrann** [eriklieben/aurelia-interactjs#3]
**I'm submitting a bug report**
- **Framework Version:**
  aurelia-framework: 1.0.0
  aurelia-cli: 0.21.0
  aurelia-interactjs: 1.0.9
  interact.js: 1.2.6

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.11.6
- **Node Version:**
  6.8.1
- **NPM Version:**
  3.10.8
- **JSPM OR Webpack AND Version**
  JSPM 0.16.46
- **Browser:**
  Chrome 54.0.2840.71 (64-bit)
  Safari 9.1.2 (11601.7.7)
- **Language:**
  ESNext

**Current behavior:**
interact-draggable.bind="dragOptions" does not work. Even though this.dragOptions is set in the constructor, this.options is undefined in the attached() method of the InteractDraggableCustomAttribute class.

**Expected/desired behavior:**
Demo: https://github.com/jeffgrann/aurelia-interactjs-test2

**Comment by martonsagi** [comment]
Could you double-check this behavior with aurelia-interactjs@1.0.10? My pull request contained fixes in connection with your problem. [@see commit](https://github.com/eriklieben/aurelia-interactjs/commit/40e659d4745ea6b4128dff473cc667211a97b56d#diff-5651c7d63eb27adc646bbcbe4725b242R19)

Thanks

**Comment by jeffgrann** [comment]
Changed `"aurelia-interactjs": "^1.0.9"` to `"aurelia-interactjs": "^1.0.10"` in my package.json and did an npm update. Now when I `au run --watch` I get the following errors:

```
{ uid: 10,
  name: 'writeBundles',
  branch: false,
  error: 
   { Error: ENOENT: no such file or directory, open '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.exports.readFileSync (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/file-system.js:49:13)
       at fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Object.load (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:832:29)
       at Object.fetch (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:822:66)
       at Object.check (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:854:30)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js',
     moduleTree: [ 'aurelia-interactjs/draggable' ],
     fileName: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-interactjs/dist/amd/draggable.js' },
  duration: [ 1, 704870893 ],
  time: 1477529828434 }
{ uid: 2,
  name: '<series>',
  branch: true,
  error: 
   { Error: ENOENT: no such file or directory, open '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.exports.readFileSync (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/file-system.js:49:13)
       at fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Object.load (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:832:29)
       at Object.fetch (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:822:66)
       at Object.check (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:854:30)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js',
     moduleTree: [ 'aurelia-interactjs/draggable' ],
     fileName: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-interactjs/dist/amd/draggable.js' },
  duration: [ 2, 25715344 ],
  time: 1477529828437 }
{ uid: 1,
  name: '<series>',
  branch: true,
  error: 
   { Error: ENOENT: no such file or directory, open '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.exports.readFileSync (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/file-system.js:49:13)
       at fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Object.load (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:832:29)
       at Object.fetch (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:822:66)
       at Object.check (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:854:30)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js',
     moduleTree: [ 'aurelia-interactjs/draggable' ],
     fileName: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-interactjs/dist/amd/draggable.js' },
  duration: [ 2, 26208055 ],
  time: 1477529828437 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { Error: ENOENT: no such file or directory, open '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.exports.readFileSync (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/file-system.js:49:13)
       at fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Object.load (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:832:29)
       at Object.fetch (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:822:66)
       at Object.check (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:854:30)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js',
     moduleTree: [ 'aurelia-interactjs/draggable' ],
     fileName: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-interactjs/dist/amd/draggable.js' },
  duration: [ 2, 26961786 ],
  time: 1477529828438 }
{ Error: ENOENT: no such file or directory, open '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.exports.readFileSync (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/file-system.js:49:13)
    at fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
    at Object.context.fileRead (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
    at Object.context.load (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
    at Object.load (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:832:29)
    at Object.fetch (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:822:66)
    at Object.check (eval at <anonymous> (/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:854:30)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/src/interact.js',
  moduleTree: [ 'aurelia-interactjs/draggable' ],
  fileName: '/Users/jeffgrann/Aurelia/aurelia-interactjs-test2/node_modules/aurelia-interactjs/dist/amd/draggable.js' }
```

**Comment by martonsagi** [comment]
Thanks for the feedback, @jeffgrann. This error message usually means that a dependency is missing or has a wrong name.
I've found out that the importation of `interact.js` has been changed from `interact.js` to `interact` [here](https://github.com/eriklieben/aurelia-interactjs/commit/0ad0795dcd79771a78140a8a39f2d52aec8f616c).

To overcome this issue, change dependency config in `aurelia.json` like this:

```
  {
    "name": "interact",
    "path": "../node_modules/interact.js/dist",
    "main": "interact"
  },
  {
    "name": "aurelia-interactjs",
    "path": "../node_modules/aurelia-interactjs/dist/amd",
    "main": "index"
  }
```

@eriklieben I saw that README contains the old `interact.js` naming for CLI. Could you update it, please? (My fork is such a mess right now, otherwise I'd send a PR). Thanks!

**Comment by jeffgrann** [comment]
Ah. Now everything works as expected and the bound options are working too. Thanks!!
